### PR TITLE
[Windows][melodic-devel] workaround WSAPoll doesn't report failed connections.

### LINKED ISSUE #151: ros::master::check() hanging
**Describe the bug**
I tried to use ros::master::check() to see if roscore is ready. But it kept hanging in this function .

**To Reproduce**
I simply ran the program quoted in https://answers.ros.org/question/236678/check-master-ros-node-is-started-c/. If I didn't start roscore at the beginning and ran it, the program never output the "waiting..." line or anything. The program got hanging forever. If I started roscore before, it would output "master started!" as expected. 

**Environment information:**
Standard installation and catkin_make followed ROSonWindows page.

### PR DESCRIPTION
**Pull request by seanyen**
This fixes https://github.com/ms-iot/ROSOnWindows/issues/151

The original problem manifests as `ros::master::check()` never return back when the `master` is not running. It turns out that it is waiting for [`WSAPoll`](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsapoll) to be returned, which is at this below line:

https://github.com/ros/ros_comm/blob/d487d5877049d61fe2ebcc6487e9a7a72d9f0346/utilities/xmlrpcpp/src/XmlRpcDispatch.cpp#L125

However, for a non-blocking socket which has a failed connection, `WSAPoll` exhibits a behavior which is not to signal this error for the caller, and with the infinite timeout, it just waits forever. There are many [discussions](https://www.bing.com/search?q=%22Windows+8+Bugs+309411+%E2%80%93+WSAPoll+does+not+report+failed+connections%22) about this behavior.

To workaround this issue, I am proposing for Windows platform adding a connection readiness pre-checks for writable sockets, which can be done by calling [`select`](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-select) and it will come back with a result immediately whether it is an `connection-error` socket or `writable-ready` socket. After we have the result, we can decide to error out or go ahead with the original `WSAPoll` to finish its job.

### CODE REVIEW

**Comment by seanyen** [comment]
@mikepurvis This is ready for review and merge. Thanks!

File: utilities/xmlrpcpp/src/XmlRpcDispatch.cpp [hunk 1]
```diff
@@ -11,9 +11,57 @@
...
+    // error out if all sockets are failed to connect.
+    return SOCKET_ERROR;
+  }
+  else
+  {
+    return WSAPoll(pfd, nfds, timeout);
+  }
 }
 
 # define USE_FTIME
```
Comment (mikepurvis) [inline utilities/xmlrpcpp/src/XmlRpcDispatch.cpp:67]: I know it's not directly related here, but in the process of reviewing this, I noticed some if/endif mismatching going on. The `#endif` at the bottom of the file is labeled for `USE_FTIME` but I believe actually corresponds to `WINDOWS`.

@seanyen Do you mind looking into this and correcting the comments if applicable?

Comment (seanyen) [reply utilities/xmlrpcpp/src/XmlRpcDispatch.cpp:67]: By checking the [commit history](https://github.com/ros/ros_comm/commit/79bfbe8f05fcf73840c88b14b6f80ee48c5a78b9), it seems to me that `USE_FTIME` was first introduced because `Windows` doesn't have `gettimeofday` so it ended up with diverged implementations. However, two years ago, a [PR](https://github.com/ros/ros_comm/pull/1249) was merged and now non-Windows implementation is in favor of `ros::ros_steadytime`.

I would say perhaps we should see if there is any opportunity to converge the implementations now, since `ros::ros_steadytime` is a portable thing and theoretically it should behave the same across the platforms.

@mikepurvis, what do you think?

Comment (dirk-thomas) [reply utilities/xmlrpcpp/src/XmlRpcDispatch.cpp:67]: Since this is orthogonal please follow up on this separately form this PR.

**Comment by dirk-thomas** [comment]
Thanks for the patch.
