### PR TITLE
fix rosconsole segfault when using ROSCONSOLE_FORMAT with  (fix #342)

### LINKED ISSUE #342: rosconsole segfault when ROSCONSOLE_FORMAT uses ${logger}
None of my ROS packages run anymore (segfault), it worked a few days ago and I didn't change the code. I did play with getting Gazebo 3.0 and drcsim working, and I switched to Groovy for a few minutes for testing Atlas. Now I'm back on Hydro on Precise. I have a local fresh roscore running. 

I have a simple program for testing:

```
#include <ros/ros.h>
int main(int argc, char** argv)
{
  std::cout << "this works" << std::endl;
  ROS_INFO("this segfaults");
  return 0;
}
```

My CMake is an empty package except this test:

```
cmake_minimum_required(VERSION 2.8.3)
project(rosconsole_dave_test)

find_package(catkin REQUIRED COMPONENTS
  roscpp
)

catkin_package()

include_directories(
  ${catkin_INCLUDE_DIRS}
)

add_executable(test_ros src/test_ros.cpp)
target_link_libraries(test_ros ${catkin_LIBRARIES})
```

When I run this binary it crashes on the ROS_INFO part. 

GDB Backtrace:

```
#0  0x00007ffff7733f2b in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff6eb58ed in ros::console::impl::getName(void*) () from /opt/ros/hydro/lib/librosconsole_log4cxx.so
#2  0x00007ffff7bc759c in ros::console::LoggerToken::getString(void*, ros::console::levels::Level, char const*, char const*, char const*, int) () from /opt/ros/hydro/lib/librosconsole.so
#3  0x00007ffff7bc6594 in ros::console::Formatter::print(void*, ros::console::levels::Level, char const*, char const*, char const*, int) () from /opt/ros/hydro/lib/librosconsole.so
#4  0x00007ffff7bc6a52 in ros::console::_print(void*, ros::console::levels::Level, char const*, char const*, char const*, int) () from /opt/ros/hydro/lib/librosconsole.so
#5  0x00007ffff6eb773f in ros::console::impl::ROSConsoleStdioAppender::append(log4cxx::helpers::ObjectPtrT<log4cxx::spi::LoggingEvent> const&, log4cxx::helpers::Pool&) () from /opt/ros/hydro/lib/librosconsole_log4cxx.so
#6  0x00007ffff699fc00 in log4cxx::AppenderSkeleton::doAppend(log4cxx::helpers::ObjectPtrT<log4cxx::spi::LoggingEvent> const&, log4cxx::helpers::Pool&) () from /usr/lib/liblog4cxx.so.10
#7  0x00007ffff699db54 in log4cxx::helpers::AppenderAttachableImpl::appendLoopOnAppenders(log4cxx::helpers::ObjectPtrT<log4cxx::spi::LoggingEvent> const&, log4cxx::helpers::Pool&) () from /usr/lib/liblog4cxx.so.10
#8  0x00007ffff69e395f in log4cxx::Logger::callAppenders(log4cxx::helpers::ObjectPtrT<log4cxx::spi::LoggingEvent> const&, log4cxx::helpers::Pool&) const () from /usr/lib/liblog4cxx.so.10
#9  0x00007ffff69e3ca7 in log4cxx::Logger::forcedLog(log4cxx::helpers::ObjectPtrT<log4cxx::Level> const&, std::string const&, log4cxx::spi::LocationInfo const&) const () from /usr/lib/liblog4cxx.so.10
#10 0x00007ffff6eb578c in ros::console::impl::print(void*, ros::console::levels::Level, char const*, char const*, char const*, int) () from /opt/ros/hydro/lib/librosconsole_log4cxx.so
#11 0x00007ffff7bc4cd8 in ros::console::print(ros::console::FilterBase*, void*, ros::console::levels::Level, char const*, int, char const*, char const*, ...) () from /opt/ros/hydro/lib/librosconsole.so
#12 0x00000000004014b0 in main ()
```

Also, I have installed from debian:
liblog4cxx10 0.10.0
liblog4cxx10-dev 0.10.0
ros-hydro-rosconsole 1.9.53

### PR DESCRIPTION
**Pull request by dirk-thomas**
@tfoote @wjwwood Please review.

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

File: tools/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp [hunk 1]
```diff
@@ -112,7 +112,7 @@ class ROSConsoleStdioAppender : public log4cxx::AppenderSkeleton
     std::string msg = event->getMessage();
 #endif
     const log4cxx::spi::LocationInfo& location_info = event->getLocationInformation();
-    ::ros::console::backend::print(this, level, msg.c_str(), location_info.getFileName(), location_info.getMethodName().c_str(), location_info.getLineNumber());
+    ::ros::console::backend::print(event.operator->(), level, msg.c_str(), location_info.getFileName(), location_info.getMethodName().c_str(), location_info.getLineNumber());
```
Comment (wjwwood) [inline tools/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp:115]: Is this the canonical way to do this? Why not just `*event`?

Comment (dirk-thomas) [inline tools/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp:115]: Because only pointers can be passed to the interface. `event` is an instance holding a pointer to the actual event object. So passing the real pointer seems to be the most straight forward way (rather then creating a pointer to a local variable / reference).

Comment (wjwwood) [inline tools/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp:115]: Ok.

**Comment by tfoote** [comment]
+1

**Comment by davetcoleman** [comment]
+1
